name: Modular Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Shared configuration
      - name: Setup base config
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: Asia/Hong_Kong
          user: "Lyam-T"
          repositories_skipped: ""
          repositories_affiliations: "owner,collaborator,organization_member"
          repositories_forks: true
          dry_run: true  # Only generates data, no output

      # Generate separate SVGs
      - name: Isocalendar SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics-isocalendar.svg"
          config_display: "columns"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugins_skip: "habits,followup"  # Skip other plugins

      - name: Followup SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics-followup.svg"
          config_display: "columns"
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugins_skip: "habits,isocalendar"

      - name: Habits SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics-habits.svg"
          config_display: "columns"
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: class
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugins_skip: "isocalendar,followup"

      - name: Commit all SVGs
        run: |
          git config --global user.name "github-actions"
          git add metrics-*.svg
          git commit -m "Update modular metrics" || echo "No changes"
          git push
          
