# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # Base setting
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_output: "png"
          config_display: columns
          config_timezone: Asia/Hong_Kong
          filename: "metrics.png"


          # Source configuration - include all your repos (public and private)
          user: "Lyam-T"

          # Repository filtering
          repositories_skipped: ""  # Clear default skips
          repositories_affiliations: "owner,collaborator,organization_member"
          repositories_forks: true  # Include forked repos

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Languages plugin
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_recent_days: 366
          
