name: Modular Metrics
on:
  schedule: [{cron: "0 16 * * *"}] # hk midnight
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Gather all the necessary data
      - name: Gather data 
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          config_output: "json"
          filename: "metrics_data.json"
          config_timezone: Asia/Hong_Kong
          user: "Lyam-T"
          repositories_skipped: ""
          repositories_affiliations: "owner,collaborator,organization_member"
          repositories_forks: true
          # Enable ALL plugins
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_habits: yes

      # Generate separate SVGs
      - name: Isocalendar SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/isocalendar.svg"
          data_from: "metrics_data.json"  # Critical!
          config_display: "columns"
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugins_skip: "habits,followup"  # Skip other plugins

      - name: Followup SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/followup.svg"
          data_from: "metrics_data.json"  # Critical!
          config_display: "columns"
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugins_skip: "habits,isocalendar"

      - name: Habits SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: "metrics/habits.svg"
          data_from: "metrics_data.json"  # Critical!
          config_display: "columns"
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: class
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes
          plugins_skip: "isocalendar,followup"
          
