# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # Base setting
          base: ""
          base_indepth: yes
          config_output: "svg"
          config_display: columns
          config_timezone: Asia/Hong_Kong

          # Source configuration - include all your repos (public and private)
          user: "Lyam-T"

          # Repository filtering
          repositories_skipped: ""  # Clear default skips
          repositories_affiliations: "owner,collaborator,organization_member"
          repositories_forks: true  # Include forked repos

          # Isocalendar plugin
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Followup plugin
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          # Habit plugin
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: class
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes


          
